### ISSUE TITLE
Non squared distance matrix as input.  

### ISSUE THREAD

**Issue by rCarto** [mthh/QgisDistanceCartogramPlugin#3]
Would it be possible to import non squared matrices?
In some cases it may be easier to collect only data for only a starting point or two than to collect the full matrix.

**Comment by mthh** [comment]
Good idea ! This will be a good reason to make a new release (I also have some other improvements in another branch).

I'll work on it next week I guess (I don't have Qgis 3, Qt 5, etc. right now).

**Comment by mthh** [comment]
Done in https://github.com/mthh/QgisDistanceCartogramPlugin/commit/04f394d1ce8da8083444329744ba13ca4e4a6d95. It will be in the `0.2` version. Thanks for the idea!
