### ISSUE TITLE
Enhance the choice of the reference entity in the list. 

### ISSUE THREAD

**Issue by rCarto** [mthh/QgisDistanceCartogramPlugin#4]
I am not sure in what order are the IDs sorted. The matrix rows order? the point layer rows order? 
It is difficult to select a single ID in a list of several hundreds unordered records...

Anyway thank you for this great plugin ! So easy to use :-)

++

**Comment by mthh** [comment]
Hum good catch..
The list of entity is currently based on the matrix rows (which already makes sense regarding to future improvements such as #3). But iirc it's stocked in a `dict`, so I guess depending on your python version it might be totally unordered (in CPython `dict` are maintaining order of insertion as an implementation detail in 3.6 and as a language feature in 3.7).

I will take care to fill the reference entity menu with features ID respecting the matrix order... it will already be an improvement but I guess the selection of a single ID in a list of several hundred of records (even if ordered) will remain difficult !

**Comment by mthh** [comment]
What I had in mind was a bunch of INSEE code (hence the difficult selection even if preserving the matrix order).
But maybe we could simply sort the list alphabeticaly or from smallest to largest value (if ID are numerics)?

Any opinion ?

**Comment by rCarto** [comment]
I would go for alphabetical order for character IDs and smallest to largest values for numerical IDs. Chance are the matrix order is rarely carefully thought....

**Comment by mthh** [comment]
The new version (0.2) is now on Qgis Python Plugins Repository : http://plugins.qgis.org/plugins/dist_cartogram/
It can also be downloaded from https://github.com/mthh/QgisDistanceCartogramPlugin/releases/tag/v0.2
