### ISSUE TITLE
Calcul des coordonnées des points images

### ISSUE THREAD

**Issue by heyberge** [mthh/QgisDistanceCartogramPlugin#5]
Bonjour,
J'ai un problème de couches qui ne sont pas dans le même système de coordonnées donc j'aimerai construire le calque de points d’image.
Quelle est la formule qui se cache dans le programme pour calculer les coordonnées des nouveaux points à partir des coefficients de déplacement ? La nouvelle distance est simple à calculer mais je ne vois pas comment calculer les cordonnées à partir de l'ancien point et la nouvelle coordonnées.
Merci

**Comment by mthh** [comment]
Désolé d'avoir oublié de répondre à votre message :-/

La méthode de calcul des coordonnées des points "images" à partir des points "sources", d'une matrice de temps de parcours et d'une entité de référence est la suivante :
- Calcul de la distance euclidienne entre le point de référence et chacun des autres points.
- Utilisation des temps de parcours et de cette distance pour calculer une vitesse entre le point de référence et chacun des autres points.
- Calcul de la vitesse médiane.
- Calcul d'un coefficient de déplacement à appliquer à chaque point : le rapport entre la vitesse associée à chaque point et la vitesse médiane.
- Déplacement de chacun des points grâce à ce coefficient de déplacement (de manière imagée, en tracant une ligne entre l'entité de référence et le point à déplacer, puis en rapprochant / éloignant le point à déplacer le long de cette ligne).

Vous pouvez consulter la documentation qui illustre cela ici : https://github.com/mthh/QgisDistanceCartogramPlugin/blob/master/help/source/index.rst (ou en cliquant sur le bouton "aide" en bas à gauche de la fenêtre du plugin).

Le code qui implémente cette logique est celui de la [fonction "get_image_points"](https://github.com/mthh/QgisDistanceCartogramPlugin/blob/master/dist_cartogram.py#L806).

En espérant que ça réponde à votre demande.
